services:
  - type: web
    name: janogoner-konthosor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: "admin123"
      - key: AGENT_TOKEN
        value: "jknews-token-2026"
      - key: SITE_URL
        value: "https://janogoner-konthosor-qv2e.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: jknews-db
          property: connectionString

databases:
  - name: jknews-db
    plan: free
    databaseName: jknews
    user: jknews_user